version: '3.9'

services:
  web-api:
    container_name: web-api
    image: akoken/web-api:1.0
    build:
      context: .
      dockerfile: Dockerfile.chiselled
      args:
        - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: quotes
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata: {}